### ISSUE TITLE
[Bug]: first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by krzlhll** [gembaadvantage/uplift#287]
### What happened?

Could not connected to the private repository. (Only HTTP is available)

$ uplift changelog
   • checking git             
   • detecting scm provider   
      ⨯ failed to parse repository remote
Error: parse "172.24.100.14:7990/scm/ipsdt/uplift-test-repo": first path segment in URL cannot contain colon

$ uplift release
   • checking git             
   • detecting scm provider   
      ⨯ failed to parse repository remote
Error: parse "172.24.100.14:7990/scm/ipsdt/uplift-test-repo": first path segment in URL cannot contain colon

### Steps to reproduce it

1. clone remote to local with http: git clone http://172.24.100.14:7990/scm/ipsdt/uplift-test-repo.git
2. Execute uplift commands without any configurations
3.
...

### Which version?

v2.18.1

### Which operating system(s) are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ga-paul-t** [comment]
Thanks for raising this issue
