### ISSUE TITLE
[Feature]: Cherry-pick commits when generating a changelog

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#300]
### Describe your feature

`uplift` provides functionality for excluding commits from a changelog through an `--exclude` flag. This works well for standalone repositories but can be problematic when mono-repos pepper the log with commits from multiple components.

`uplift` should provide a mechanism where it is possible to select (or cherry-pick) explicitly commits from the git log when generating a changelog.

### Your potential solution

Introduce a new `--include` flag capable of cherry-picking commits.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by canidam** [comment]
Having both `--include` and `--exclude` options is an important capability. From client perspective, I think the appropriate behavior should be:
1. `--include` implicitly states you want to exclude everything else
2. You can support both `--include` and `--exclude` in the same execution. This will allow excluding some commits from the subset included commits. For example, `--include myService --exclude wip` will first filter commits that includes `myService`, and afterwards exclude from that set commits matching the `wip`. The result is what you want to show in the CHANGELOG.

WDYT?

**Comment by ga-paul-t** [comment]
I agree with everything you have said here. I have almost finished implementing this feature as described. 😄

**Comment by canidam** [comment]
@ga-paul-t I think there's a bug here; when I'm running `--include` with multiple params, the logic is AND instead of OR.

```
func filterCommits(commits []git.LogEntry, regexes []string, filter commitFilter) ([]git.LogEntry, error) {
	filteredCommits := commits
	for _, regex := range regexes {
		rgx, err := regexp.Compile(regex)
		if err != nil {
			return filteredCommits, err
		}
		filteredCommits = filter(filteredCommits, rgx) # the bug is here
	}

	return filteredCommits, nil
}
```

The loop iterates over `commits`, and filters them each time, passing the **filtered commits** instead of the original ones. This causes **AND** between the regex patterns, usually ending with an empty list.

**Comment by ga-paul-t** [comment]
Thanks for spotting this. Serves me right for coding at 5 am. A bit of shameful cut and pasting there :blush:

**Comment by canidam** [comment]
I pushed a possible fix for this 😄 indeed it looks like these can be abstracted as they share most of the code, but their logic is different. So it can't work with a `commitFilter` function.
