### ISSUE TITLE
[Bug]: Invalid magic: gzip during download of the script file to install tag v2.21.0

### ISSUE THREAD

**Issue by jimdevops19** [gembaadvantage/uplift#320]
### What happened?

I tried to install uplift using the raw version within the scripts directory but ended up with a similar issue in an alpine container and in an Ubuntu host.
This is the command I tried to use in order to to a one-liner installation:
```
curl https://raw.githubusercontent.com/gembaadvantage/uplift/main/scripts/install | bash -s -- -v v2.21.0
```

I received the following error:
```
tar: This does not look like a tar archive
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to install uplift
```

Is a decompress step required before extracting the download tar file? Thanks for the help

### Steps to reproduce it

1. Tried to re-install gzip and tar on my system
2. Tried to first download the script file using curl <URL> -o <output_file> and made some debugging for printing the variables.

### Which version?

2.21.0

### Which operating system(s) are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ga-paul-t** [comment]
👋 @jimdevops19, thanks for raising this issue. I will take a look shortly

**Comment by jimdevops19** [comment]
I guess I understand more what happens now.
It seems from this line that defines the local archive variable, that the convention of the complete tar file is not matching what you hold in the releases of the repo.
https://github.com/gembaadvantage/uplift/blob/main/scripts/install#L87

This is the problematic line:
```
uplift_${TAG#v}_${OS}-${ARCH}.${PACKAGE_TYPE}
```

I see from the releases, that the convention is like the following (For Linux, at least)
```
uplift_${TAG#v}${OS}_${ARCH}.${PACKAGE_TYPE}
```
The **TAG** and the **OS** are not separated by under-score, and also the hyphen between **OS** to **ARCH** should be an underscore.

Once I modified the variable the way I described. It installed it perfectly. Lemme know if to submit a merge request on this one :)

**Comment by ga-paul-t** [comment]
Looks like this problem was introduced accidentally through a change within the `.goreleaser.yml` file. I'll recreate the release shortly, ensuring the previous convention remains. And the script will work as expected

**Comment by ga-paul-t** [comment]
@jimdevops19 that should now be sorted

**Comment by jimdevops19** [comment]
@ga-paul-t Thank you very much for the quick response and fix really appreciated! 🙏
