### ISSUE TITLE
[Feature]: add support for bumping xml files

### ISSUE THREAD

**Issue by ga-shoaib-w** [gembaadvantage/uplift#354]
### Describe your feature

If we could add support for bumping xml files, it will support java projects using maven. 

### Your potential solution

implement a xml path traversal tool to bump versions where applicable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by autotmp** [comment]
A bit sad to see this get the **wontfix** label - would have been great for my teams using C# to update`csproj`/`props` files. Any chance this gets revisited @ga-paul-t or @ga-shoaib-w ?
