### ISSUE TITLE
[Feature]: Add command for generating a changelog

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#42]
### Describe your feature

Uplift currently supports the tagging of repositories and the bumping of files based on the last conventional commit. However, it is missing the ability to generate a changelog, capturing all of the changes between the last 2 tags of a repository.

Initial implementation should just focus on the creation of a changelog between 2 fixed points, i.e. the last 2 tags of a repository

### Your potential solution

Add a new `changelog` command

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nbrugger-tgm** [comment]
Hi, as i see you are currently working on implementing the changelog.

I think it would be cool if it was possible to also somehow get the diff (just a changelog for the version itself). And since you seem to implement it in a diff based way this should not add too much effort. If this is out of the scope of this ticket, i would be willing to contribute a PR, my knowledge about GO is limited tho

**Comment by ga-paul-t** [comment]
I have almost finished the current implementation, which generates a changelog, loosely based on the https://keepachangelog.com/en/1.0.0/ format.

```text
# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

## [0.1.0] - 2021-11-18

a2a7125 commit
b754a23 commit
```
Is your request that the changelog command would just output the diff to stdout for example? I assume the diff would effectively be:

```text
## [0.1.0] - 2021-11-18

a2a7125 commit
b754a23 commit
```

**Comment by nbrugger-tgm** [comment]
> Is your request that the changelog command would just output the diff to stdout for example? I assume the diff would effectively be:
> 
> ```
> ## [0.1.0] - 2021-11-18
> 
> a2a7125 feat: latest new feature
> b754a23 docs: update readme
> ```

Exactly.

Something along this lines: 
```shell
uplift changelog --diff-out=release.md
uplift changelog --print-diff
uplift changelog --diff-only
```

**Comment by ga-paul-t** [comment]
I am going to raise this as a separate issue. Going to combine this work with the introduction of a `--silent` flag, that allows uplift to be output directly into a bash variable for example, e.g. `TAG=$(uplift tag --silent)`
