### ISSUE TITLE
[Feature]:  support different locations for uplift configuration file

### ISSUE THREAD

**Issue by j-flat** [gembaadvantage/uplift#76]
### Describe your feature

Ability to read configuration file from configuration specific folder (.config).

We have a use-case where there are several tools added to the repository and all of these have their specific configuration files. These files will increase the number of files on the repository root, and where some tools support defining non-default configuration locations, others don't. This change could enable cleaner repository structures. 

With the small change to the current implementation, configuration files could be iterated from repository root and .config-folder, without changing a lot of the existing functionality.

### Your potential solution

On the `cmd/uplift/config.go` where the possible configuration files are iterated over, nested loop would allow to iterate over several folder options. Following would demonstrate it with root of the repository as well as .config-folder:

```go
var (
	folders = [2]string{"./", ".config"}
	files   = [4]string{".uplift.yml", ".uplift.yaml", "uplift.yml", "uplift.yaml"}
)

func loadConfig() (config.Uplift, error) {
	for _, file := range files {
		for _, folder := range folders {
			cfg, err := config.Load(fmt.Sprintf("%s/%s", folder, file))
			// If the file doesn't exist, try another, until the array is exhausted
			if err != nil && os.IsNotExist(err) {
				continue
			}

			return cfg, err
		}

	}

	return config.Uplift{}, nil
}
```

### Any additional information?

I have forked this repository and opened a pull request on my forked repository towards the fork, but in case this kind of change could be applied to **uplift**, I could change the Pull Request to point to the original repository. 

I have added unit-test changes to my implementation as well.

The Pull Request is here: [https://github.com/j-flat/uplift/pull/1](https://github.com/j-flat/uplift/pull/1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ga-paul-t** [comment]
Hi. Thanks for raising the feature. Do you have an example of one of these other tools that you use? Do they provide the location of the config file through a command-line argument?

I do like the idea of this. And I think your use case is definitely one that would be experienced by many other people. I am wondering whether a better way of doing this would be to use cobra to define a global flag, something like `--config` or `--config-file` and then make use of the Cobra hooks to ensure the config is loaded before any commands are run.

It's late, I'll have a think in the morning :smile:

**Comment by j-flat** [comment]
Hi!

The ones where I use it now is [terraform-docs](https://github.com/terraform-docs/terraform-docs) & [pre-commit](https://pre-commit.com/#intro). I'm setting up a Terraform boilerplate structure, that would not only do things such as linting and security scanning of the terraform code but also enforce Conventional Commits and help to maintain CHANGELOG and Semantic Versioning, hence interested in **uplift**.  In my use case, I will likely end up having 5-8 of these configuration files and I wished to push them out of sight into the configuration dedicated folder 😅 

I'm partly sad that someone picked up this feature request because I 100% agree with you, I was thinking that approach after I closed the computer and wanted to work on it this morning. I also forgot to update README.md for my forked repository, so the PR was not complete anyhow. 

Although in order to make it backward compatible, I guess the change should support all the old possible configuration namings, so the global flag would only specify the location of the file, not the entire path to it? 

Then the flag could have default pointing to a root of the repository & the old loop would try to find one of the four possible files. If the value would be something else, that directory would still require to have the file with one of the expected names.

**Comment by ga-paul-t** [comment]
Morning @j-flat. I was just experimenting with the idea this morning also. Have pushed my changes to a branch on this repo. I am happy if you want to deliver this functionality.

I was going for 2 global command-line arguments:

- `--config-dir`: pass in an optional config directory, and the resolution of config files will happen in that location
- `--config-file`: an exact location to a config file
